settings: properly handle type(None)
When converting values to the same type None must be treated specially since we
can't create instances from it:

    TypeError: cannot create 'NoneType' instances

Ideally we would do type conversion on lists too but since it's not possible to
pass a list through jsonarg, json, str or raw parameters in ansible we have to
pass it as string and live with the changed item due to different types.